### ISSUE TITLE
app crash at startup

### ISSUE THREAD

**Issue by mohShah96** [cafebazaar/PoolakeyUnitySdk#5]
My app crashes when trying to initialize the plugin.
It just happens the first time I open the app.
The next time I open it, it works ok...
I added some logs, and I found out that the crash is happening when I'm trying to initialize the payment object.

`Debug.Log("[BazaarMarketManager]: Initialize 0 ");`
`var securityCheck = SecurityCheck.Enable(_publicKey);`
`Debug.Log("[BazaarMarketManager]: Initialize 1 ");`
`var paymentConfiguration = new PaymentConfiguration(securityCheck);`
`Debug.Log("[BazaarMarketManager]: Initialize 2 ");`
`_payment = new Payment(paymentConfiguration);`
`Debug.Log("[BazaarMarketManager]: Initialize 3");`

right there...before the last log...

**Comment by manjav** [comment]
Hi Mhammad
I need logs from logcat

**Comment by mohShah96** [comment]
> Hi Mhammad I need logs from logcat

![Uploading IMG_20220316_151323_399.png…]()

**Comment by mohShah96** [comment]
> Hi Mhammad I need logs from logcat

![IMG_20220316_151321_136](https://user-images.githubusercontent.com/35012433/158584300-f5f97479-e901-40ef-8a22-d7a119261696.png)
![IMG_20220316_151323_399](https://user-images.githubusercontent.com/35012433/158584307-049c57b9-ab5c-4872-a879-ee0a1aa71ade.png)

**Comment by manjav** [comment]
Tell me about your android version and device model.
